### ISSUE TITLE
404 Error on Windows build

### ISSUE THREAD

**Issue by stukkat** [agersant/polaris#122]
OS : Windows 10
Polaris version : 0.13.0

As the title suggests, a 404 error is found when I navigate to http://localhost:5050/
where the previous polaris build would present a login page.

**Comment by agersant** [comment]
Thanks for the report. The 0.13.0 Windows installer does look very broken. I'm investigating.

**Comment by agersant** [comment]
Fixed in ea7edea79bd21989bcd8b0cf26c8a7638c101791 and published as version `0.13.1` 😓. I'll open a follow-up ticket for a better long term solution.

Note that if you run Polaris as administrator, the `0.13.0` server may have created a `C:\Users\runneradmin` folder. This folder is safe to delete.

@stukkat  Please let me know if this fix works for you!

**Comment by stukkat** [comment]
Tested and everything seems to be in order. Thank you @agersant :)

**Comment by stukkat** [comment]
Tested and everything seems to be in order. Thank you @agersant :)
