### ISSUE TITLE
[Doc] Is it possible to build the backend independently?

### ISSUE THREAD

**Issue by winston0410** [agersant/polaris#158]
Hi I have a question that I cannot find anywhere in doc, I don't find a better place to ask so I am going to ask here.

Is Polaris monolithic? I want to run the server on a small VPS, and serve the frontend on a different machine. Is it possible to use `cfg` to strip all routes for serving HTML if it is monolithic?

**Comment by agersant** [comment]
Hello!

This isn't something that is formally supported via configuration, but it should be fairly straightforward to cobble together if you want to try. Here are the involved moving parts:

To run a Polaris server without it serving the frontend:
- This [line of code](https://github.com/agersant/polaris/blob/e2bf97db99c56cc0f5bb137831d2d85494fb38fb/src/service/actix/mod.rs#L41) is setting up the frontend file serving in the server source and can be removed.
- The `web` directory in the release tarball can also be safely removed.
- If you use the supplied [makefile](https://github.com/agersant/polaris/blob/master/res/unix/Makefile) to install Polaris, also remove every line that contains `POLARIS_WEB_DIR`

To host a Polaris frontend (without server):
- Simply serve the `web` directory that is part of the release tarball
- You will have to setup redirections on your web server so that requests to `/api/...` from the frontend are routed to your actual Polaris server

This is very much untested so I'm curious how it goes it you try it out!
