### ISSUE TITLE
Add the ability to run Polaris on some HTTP root path

### ISSUE THREAD

**Issue by johnflan** [agersant/polaris#180]
Would it be possible to optionally define a root path component so
http://192.168.0.2:5050/#/browse becomes http://192.168.0.2:5050/<DEFINED_PATH>/#/browse

This means it is easier to host this service on a shared URL with other services. 

Vaultwarden for example calls this alternate base dir - https://github.com/dani-garcia/vaultwarden/wiki/Using-an-alternate-base-dir

**Comment by mzagrabe** [comment]
Heya @johnflan 

Are you planning on having the polaris executable also serving <SOME_OTHER_PATH>/application_2? Because you already have a unique URI component in the listening TCP port (5050) that can identify the polaris URL.

I have apache reverse proxy in front of polaris to get the URL that I desire.

-m

**Comment by johnflan** [comment]
yeah I do run other apps on the same host, it can be resolved with URL rewriting but its a bit messy

**Comment by agersant** [comment]
Not planning to implement this, as it makes implementing clients more complex and can be handled w/ reverse proxy setups.
