### ISSUE TITLE
Last.fm 502 Bad Gateway

### ISSUE THREAD

**Issue by VlaK0r** [agersant/polaris#220]
Hello!
Thank you for your hard work!

An error occurs when connecting the service. (502 Bad Gateway)

![Снимок экрана_20241011_141730](https://github.com/user-attachments/assets/c90dd72f-5922-400a-92f3-1da3d0a2067f)

**Comment by agersant** [comment]
Hello!

I did notice this a couple weeks ago too. There is nothing wrong with your setup or last.fm account as far as I know. I believe something changed on the last.fm side, as this exact flow used to work. I wasn't able to find any kind of public changelog from them either.

I do have some bad news regardless, which is that last.fm integration will be discontinued in the next major Polaris release. I know this is annoying, and I didn't make this decision lightly (I am also using this integration!). The reasons are that:

- The Rust library to interface with last.fm is abandoned (ignoring my basic maintenance PRs)
- I don't want to spend time and energy supporting for-profit closed platforms anymore (still supporting Windows/Android due to ubiquity 😥)
- It's borked (as you discovered)


(closing the ticket since I am not planning to action on it, but happy to continue the conversation)

**Comment by VlaK0r** [comment]
> (closing the ticket since I am not planning to action on it, but happy to continue the conversation)

Yes, I also have not used Lastfm for a long time. I'm more interested in [maloja](https://github.com/krateng/maloja).

**Comment by VlaK0r** [comment]
> (closing the ticket since I am not planning to action on it, but happy to continue the conversation)

Yes, I also have not used Lastfm for a long time. I'm more interested in [maloja](https://github.com/krateng/maloja).

> in the next major Polaris release

Can we find out what changes and improvements await us?

**Comment by agersant** [comment]
I keep this board up to date as I'm working on it: https://github.com/users/agersant/projects/2/views/1

Maloja looks neat. I haven't explored the OSS ecosystem for scrobbling but I would be interested in (re)adding something to Polaris to fill this niche eventually.

**Comment by FoxxMD** [comment]
@agersant my open-source application [multi-scrobbler](https://foxxmd.github.io/multi-scrobbler) can handle scrobbling for Polaris but would require some additions to the API. MS requires the music Source to have either:

1. an endpoint containing history of music listened to (that is eligible to scrobble, like last.fm) or
2. an endpoint that returns real-time data about music being played on the application (like [subsonic's `getNowPlaying()`](https://subsonic.org/pages/api.jsp#getNowPlaying) but ideally like [spotify's Get Playback State](https://developer.spotify.com/documentation/web-api/reference/get-information-about-the-users-current-playback) that includes player position/progress)

I've installed polaris and don't see any information like this surfaced from the OpenAPI docs. Please consider implementing this in the future.

**Comment by agersant** [comment]
Thanks for the suggestion, this looks very promising! 
Ticketed here: https://github.com/agersant/polaris/issues/234
