### ISSUE TITLE
Linux system-wide install guidance

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris#39]
I tried to do a system-wide install on Linux and it's a bit of a mess. I ended up with this:

```
/var/lib/polaris
/var/lib/polaris/.local
/var/lib/polaris/.local/share
/var/lib/polaris/.local/share/polaris
/var/lib/polaris/.local/share/polaris/polaris.log
/var/lib/polaris/.local/share/polaris/polaris.pid
/var/lib/polaris/.local/share/polaris/thumbnails
/var/lib/polaris/.local/share/polaris/thumbnails/12698004523255186174.jpg
/var/lib/polaris/.local/share/polaris/thumbnails/11339598049783905663.jpg
/var/lib/polaris/.local/share/polaris/thumbnails/17518483773397318633.jpg
/var/lib/polaris/.local/share/polaris/db.sqlite
```

The `.local/share` part shouldn't be there, the log file should be under `/var/log`, and the PID file should be under `/var/run`.

This one isn't great, but it would be nice to include a `systemd` unit in the package. This can be used as a starting point.

```ini
[Unit]
Description=Polaris
After=network.target

[Service]
User=polaris
ExecStart=/usr/bin/polaris -f -w /usr/share/polaris/web -s /usr/share/polaris/swagger
WorkingDirectory=/var/lib/polaris

[Install]
WantedBy=default.target
```

**Comment by agersant** [comment]
How did you end up with things under /var/lib? The Makefile tries to put thing under your home directory, following a structure which I found recommendations for when I looked it up (example: https://unix.stackexchange.com/questions/316765/which-distributions-have-home-local-bin-in-path). If you have a suggestion for a solution that is more standard across distributions, changes are welcome. I am more of a Windows developer so it's a bit hard for me to figure out what the best practices really are.

Does most software come with a `systemd` unit file? I thought that was something which would be added when packaging for a specific distro / package manager.

**Comment by lnicola** [comment]
I wanted to run Polaris as a daemon, under its own user. `~/.local` and `~/.config` are perfectly fine for software that's run by multiple users; your desktop environment or text editor might keep their settings there. But if you have a system-wide daemon, the conventions are to:

- keep logs under `/var/log` or `/var/log/app`
- keep mutable state under `/var/lib/app`
- keep immutable files under `/usr/share/app`
- keep transient files under `/run/app`

See https://www.freedesktop.org/software/systemd/man/file-hierarchy.html for more information.

> Does most software come with a systemd unit file? I thought that was something which would be added when packaging for a specific distro / package manager.

A lot of software does. Before `systemd`, you needed shell scripts that were often distro-specific, so it didn't really make sense for the maintainer to provide an upstream init script. Now `systemd` is used by most distributions (Ubuntu, Debian, CentOS/RHEL/Fedora, OpenMandriva and Arch Linux, at least), so its unit files are pretty portable. Even if not everyone is using `systemd`, it doesn't hurt to have a sample unit in the repository for packagers or users from other distros.

**Comment by fgaz** [comment]
I'm trying to package polaris for NixOS, but I'm having some problems with `web` and `swagger`. I'd like to include those in the package, but a package can't modify the user's home directory, and the default search path for them is under `~`, so I have to either patch the source to make it search in a system directory first, or wrap the program with a script that hardcodes `--web` and `--swagger`. Both solutions have their problems though, so it'd be great to have a way to set the default web/swagger path at install time.

**Comment by agersant** [comment]
Thanks for reviving this issue, I did let it linger a lot longer than I should have. I am very interested in having Polaris available through a package manager too. Please let me know if/when you succeed and we can add it as a possible installation method in the `README`.

I just opened a PR, guided by @lnicola's suggestions and by https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard. Testing and feedback would be very welcome on this as I don't have a very convenient setup to validate this work myself. The testing process would look like:
- Clone the `directories` branch of `polaris`
- Download ([from Github](https://github.com/agersant/polaris-web/releases)) and unzip a build of `polaris-web`. It should be a 'web' directory within the cloned `polaris` repo.
- From the `polaris` repo top-level directory, run `./res/unix/release_script.sh`
- You should end up with an archive under `./release`, which is what we would publish for end users
- Follow the install process from the README (aka. `make install`)
- Check that Polaris works and files end up in the expected locations (see updated README in PR #91)
- Run the uninstall command and make sure everything is gone

@fgaz  Specifically for NixOS, I am not sure this will get us all the way through. I just read that NixOS doesn't follow the Linux Filesystem Hierarchy Standard linked above, although it is unclear to me if the differences will be relevant here.
I am happy to consider adding options to the install script (which is currently very trivial), but it looks like moving the goalpost to the next step. How would the Polaris executable know where to find the locations that were used at install time to store the `web` and `swagger` static files? Polluting user systems with an environment variable for this seems a little inelegant.

**Comment by fgaz** [comment]
@agersant the usual way to do this is to use variables such as `PREFIX` and `BINDIR` in the makefile, so that distributions can override them with their preferred locations: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
Usually build systems offer a way to encode that variable in the executable (for example in C you can do something like `$(CC) -DDEFAULT_WEB_PATH=$(DATADIR)/web`)

**Comment by fgaz** [comment]
From a quick search it looks like it can be done with compile time environment variables! https://stackoverflow.com/questions/51620782/is-it-possible-to-initialize-a-variable-from-an-environment-variable-at-compilat/51620853#51620853

**Comment by agersant** [comment]
Ah yes, this approach makes perfect sense. I think a good Rust equivalent of `-D` compiler flags would be [option_env](https://doc.rust-lang.org/std/macro.option_env.html) which can read environment variables at compile time. This solves the implementation problems nicely.

On the configuration front, I am trying to map these GNU installation variables to what Polaris needs:
- `POLARIS_BIN_DIR` would use `bindir`
- `POLARIS_STATIC_DIR` (where web and swagger files go) would use `datadir`
- `POLARIS_DB_DIR` would use `localstatedir` - although this would mean `/usr/local/var/polaris` by default instead of `/var/lib/polaris` which was suggested by the filesystem hierarchy standard.
- `POLARIS_PID_DIR` would use `runstatedir` - the documention here is confusing as where this would end up by default (`/var/run/polaris` or `/usr/local/var/run/polaris`?). Neither of them is `/run/polaris` as suggested by the filesystem hierarchy standard.
- I don't see applicable standard variables for `POLARIS_LOG_DIR` and `POLARIS_CACHE_DIR`

Also, are these variables guaranteed to exist on all Linux systems or should I provide fallback locations?

**Comment by fgaz** [comment]
I'm not sure about `localstatedir`. While the `/` - `/usr/local/` split is widely accepted for read-only files, I've actually never seen `/usr/local/var` in the wild. I guess you could set `/var` as default `localstatedir` (I see lots of packages doing this) and then put web and swagger in `$(localstatedir)/lib/polaris/`. Usually logs are under `/var/log/` while caches are under `/var/cache/`, so you can use `localstatedir` for those too.

Yes, you should provide fallbacks

**Comment by agersant** [comment]
I updated the PR following your advice, could you take another look at the Makefile (and the rest if you're curious)?

**Comment by ogarcia** [comment]
As side note, for user installation I think that must fulfill the [XDG standard][1].

About this, IMHO:
- Database must be in: `$XDG_RUNTIME_DIR` (default `$HOME/.local/share`)
- Thumbnails must be in: `$XDG_CACHE_HOME` (default `$HOME/.cache`) since can be regenerated if deleted, logs must be in $XDG_CACHE_HOME too since this directory is for "user specific non-essential data files"
- PID must be in: `$XDG_RUNTIME_DIR` this has not default, can fallback to /tmp or similar directory the important is that this directory MUST have 700 permissions and MUST be deleted after a reboot.

About `$XDG_RUNTIME_DIR`, systemd defines `/run/user/$UID` as it, so you can define `$XDG_RUNTIME_DIR/polaris` and fallback to `/tmp/polaris-$UID` if `$XDG_RUNTIME_DIR` is not defined.

If you follow the specifications the default must be:
```
/var/lib/polaris/.local/share/polaris/db.sqlite -> $XDG_RUNTIME_DIR/polaris for database
/var/lib/polaris/.cache/polaris/thumbnails/12698004523255186174.jpg -> $XDG_CACHE_HOME/polaris
/var/lib/polaris/.cache/polaris/polaris.log -> $XDG_CACHE_HOME/polaris
/run/user/$UID/polaris/polaris.pid -> $XDG_RUNTIME_DIR/polaris or fallback to /tmp/polaris-$UID
```

[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by agersant** [comment]
The [XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and the [GNU standard](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) are in complete contradiction so it's going to be difficult to accommodate both.

After a lot of reading, this is the pros and cons I see in each of these standards:

- XDG is a much simpler and cleaner standard than the GNU installation directories
- The GNU installation process is more customizable, which is nicer for package maintainers (like @fgaz)
- Usage of the GNU installation directories is more widespread (eg. XDG directories are not set on [stock Arch Linux](https://wiki.archlinux.org/index.php/XDG_user_directories#Installation))
- The XDG standard does not specify where essential but non-user-specific files (polaris-web and swagger files) should go
- The XDG standard does not specify where the program executable should go
- The XDG standard does not specify a fallback for `$XDG_RUNTIME_DIR`
- The XDG standard is ambiguous when it specifies where log files should go ([citation](https://stackoverflow.com/questions/25897836/where-should-i-write-a-user-specific-log-file-to-and-be-xdg-base-directory-comp))

Overall, this comparison makes me want to use the GNU standard over XDG.

However, you do bring up a good point in that it should be easy for users to figure out how to install Polaris within their home directory. I suggest solving this with the addition of an alternative install command, `make install-xdg`, which would use the following directories:

- `$XDG_DATA_HOME/polaris/…` (w/ standard fallback) for the executable, static files (polaris-web and swagger) and log file
- `$XDG_CACHE_HOME/polaris/thumbnails` (w/ standard fallback) for thumbnails
- `$XDG_RUNTIME_DIR/polaris/polaris.pid` for the pid file or the `/tmp` fallback you suggested

I think this solution gets us the best of both worlds in that:

- XDG compliant installation is available as a zero-config one-liner, which we can recommend in the docs for users without admin rights or trying to avoid a system-wide install.
- Customizable GNU-standard installation is available for package maintainers and users who want a system-wide install.

Would this work for you?

**Comment by fgaz** [comment]
Sorry for the late reply!

> The XDG standard and the GNU standard are in complete contradiction so it's going to be difficult to accommodate both

As far as I know, the gnu standard is for system, while xdg is for user stuff, so it makes sense that they are in conflict

> The XDG standard does not specify where essential but non-user-specific files (polaris-web and swagger files) should go

For user installations, it'd probably be in `.local/share`, like you suggested. There is no real distinction between static and dynamic stuff there, unlike with /usr and /var. Not sure about `$XDG_RUNTIME_DIR`, but what you proposed is probably ok

> The XDG standard does not specify where the program executable should go

User-level installations usually put executables in custom locations or -better- `~/.local/bin`

> make install-xdg

sounds good! (if it doesn't have a high complexity/maintenance cost on the makefile of course. not sure how easy it is to set variables in a target while allowing overrides)

But really, as maintainer and user the most essential things would only be:

* The location of static files must have a default set at compile time
  * possibly with standard presets (basically $PREFIX/share/..)
* There must be a way to set _all_ the locations of dynamic files (db, logs, cache, pid) at runtime, so that they can be set to custom / user-writable locations

The first point is extensively solved in the pr, but for the second it's currently only possible to set the db path as far as I can see

**Comment by agersant** [comment]
https://github.com/agersant/polaris/pull/91 has been merged 🥳
