### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by irevoire** [agersant/polaris#50]
We should do a new release of Polaris since it currently does not compile with the latest rust compiler and rocket being in version 0.4.0.

**Comment by lnicola** [comment]
What compiler are you using? It works for me with the latest nightly.

**Comment by irevoire** [comment]
I’m using: rustc 1.40.0-nightly (7979016af 2019-10-20)
With: polaris-0.10.0.tar.gz

**Comment by agersant** [comment]
It's a good point though, the latest release is fairly out of date. I was holding out until Rocket 1.0 but that doesn't seem to be coming out just yet. I'll make one within the next couple weeks.

**Comment by agersant** [comment]
Apologies I haven't gotten to this yet, I did not forget but I have been very busy.

**Comment by agersant** [comment]
I have noticed some critical issues while testing latest where the web UI is not being served correctly outside of localhost (I think due to hyper/rocket bugs). Will hold off to make a release until that's solved (most likely with next release of Rocket).

**Comment by lnicola** [comment]
I'm using a bit of an older version, but it worked fine for me. The only issue is the session handling: if it expires, the UI won't work. This is filed as #36.

**Comment by agersant** [comment]
What I'm seeing is a lot worse, the server is failing to respond when receiving rapid-fire requests (such as a browser requesting all the JS files for the web UI).

I originally thought it was an issue with my networking setup but investigations (which you can follow here https://www.reddit.com/r/selfhosted/comments/dduaug/routing_issue_i_think_to_selfhosted_web_server ) seem to indicate otherwise. IIRC you run your Polaris instance behind a nginx reverse proxy which might be shielding you from this problem?
I also saw some issues on the Rocket bug tracker which could be related (100x performance downgrade on 0.4, issues with HTTP keep-alive) but I haven't found a conclusive workaround.

**Comment by lnicola** [comment]
I wasn't able to reproduce your issue while connecting to it from the LAN (but without `nginx`). Something strange happened, though: my `users` table seems to have been truncated. I re-created my user and the other tables (`directories`, at least) are fine.

**Comment by agersant** [comment]
The issue doesn't happen on LAN for me either so that's a bit inconclusive.

For the users table, that's because of 8dbaad98f55384a02e3c6ca0cc50b7f8940d9b04. It's a (light) breaking change that I will mention in the release notes.

**Comment by lnicola** [comment]
Still works fine for me outside the LAN using port forwarding.

**Comment by agersant** [comment]
I guess it's good news that this bug is local to me. I'll move forward with the release ASAP then (I'm travelling for the holidays but I should be able to do it at some point in the middle of that).

**Comment by agersant** [comment]
Just released version 0.11.0 🥳
