### ISSUE TITLE
Supported apps / API?

### ISSUE THREAD

**Issue by khromov** [agersant/polaris#6]
Hi! 

Are there any Android or iOS apps for Polaris? I believe this is the primary use case for most users. 

Is there an API and is it documented? The Wiki link on GitHub does not work.

**Comment by agersant** [comment]
Hi!

There is indeed an Android app, the repository is over here: https://github.com/agersant/polaris-android
It's been in alpha for a couple months now. I use it every day and the main reason it's still in alpha is that it needs more testing (especially on devices other than my phone). If you have any interest in using it, please let me know and I'll be happy to add your email to the list of alpha testers for the app on the play store.

There is no iOS app in development.

There is an API and I've been writing it with the goal of other people being able to write their own clients eventually. It is not documented yet and documenting it hasn't been a priority because the project still has a small audience. If you're interested, I'd be happy to make that documentation a priority. Until then, your best bet is looking at the source in https://github.com/agersant/polaris/blob/master/src/api.rs which has all the API endpoints.

**Comment by khromov** [comment]
That sounds really exciting! I can help you test it on multiple Android devices. My Play account is <firstname>.<lastname>@gmail.com, substitute the names. :-)

**Comment by agersant** [comment]
I've just added you to the list of testers, you should be able to grab the app from the Google Play Store at this URL: https://play.google.com/apps/testing/agersant.polaris

Let me know if this works. Feel free to open Github issues (or PR) for any problems you encounter!

**Comment by deathspawn** [comment]
Can I also help test? I have a Moto Z Play Droid and an Asus Z580CA. My email is deathspawn989 AT gmail.

**Comment by agersant** [comment]
@deathspawn I've just added you to the alpha, the URL to download the app is in my previous post. Please let me know if it works out on your devices! If not, please write something up on https://github.com/agersant/polaris-android/issues and I'll get to it eventually.

Out of curiosity, how did you find out about Polaris?

**Comment by brendan-r** [comment]
Thanks so much for writing this (I'm very glad/impressed that it's in Rust)!

I just wanted to ask, given the number of clients which already exist for Subsonic/Ampache, is there any desire to make the Polaris APIs compatible, so that Subsonic clients can speak to a Polaris server? I know that Polaris has different goals (e.g. to be a lot more minimal), so perhaps this isn't a good idea. Regardless, thank you for working on it! :)

**Comment by agersant** [comment]
Thanks a lot for your comment! It makes me super happy to see more people sharing interest in Polaris <3

I am OK adding complexity to Polaris as long as the additional features stay compartmentalized (like the YDNS support impacts no other code) and invisible to users that don't want it.

Exposing a Subsonic API is something I have considered. There would obviously be holes in it for the many features of Subsonic that don't have a Polaris equivalent, but it is doable. It's a pretty large task though (because the Subsonic API is very big) so don't hold your breath for it.

**Comment by agottschling** [comment]
Any chance I can get it on this app? Play account is FIRSTNAMEmLASTNAME@gmailDOTcom. Just substitute in from my Github profile.

**Comment by agersant** [comment]
@agottschling The Android client is now in public beta. You can find it [over here](https://play.google.com/apps/testing/agersant.polaris). Let me know if this works for you!
