### ISSUE TITLE
Add opus format support

### ISSUE THREAD

**Issue by vvrein** [agersant/polaris#63]
Rust already has binding for libopus https://docs.rs/opus/0.2.1/opus/  
I don't know if this would help anyhow, but opus support for polaris would be very nice :)

**Comment by agersant** [comment]
Opus uses vorbis comments for metadata (which Polaris already supports) so this should be a simple addition. Thank you for the suggestion!

**Comment by agersant** [comment]
Not as trivial as I was hoping, while the vorbis comments format is the same as ogg, that doesn't mean we can just throw an opus file at lewton and get vorbis comments back.

This will require writing a new crate just for this purpose I'm afraid. @RustAudio in case someone over there has suggestions.

**Comment by vvrein** [comment]
Thanks for reply! 
Since there is no urgent need for opus support, and I don't know rust :) this issue can be suspended until someone interested in it will be found :)

**Comment by vvrein** [comment]
idk whether this would be helpful, but here one project that seems can read opus format:
https://github.com/izderadicka/audioserve

**Comment by agersant** [comment]
Unfortunately, it looks like they get their metadata through `ffmpeg` (https://github.com/izderadicka/audioserve/tree/master/crates/media_info). I would prefer avoiding this, as it's very heavyweight and would complicate the build process for Polaris.

**Comment by vvrein** [comment]
Ok, I see 🙂

**Comment by zaethan** [comment]
Do you only need the comments/metadata to support opus?
Based on this issue, I have written a small parser (as a rust exercise for myself), which just takes something that implements the Read trait (like a BufferedReader) and spits out the opus headers (if it found any). The comment header then contains a map with all the comments.
I would upload it to github, if this is what you need.
Here is an example of the returned headers (I just entered some garbage as comments when creating the file):

```
OpusHeaders {
    id: IdentificationHeader {
        version: 1,
        channel_count: 1,
        pre_skip: 312,
        input_sample_rate: 48000,
        output_gain: 0,
        channel_mapping_family: 0,
        channel_mapping_table: None,
    },
    comments: CommentHeader {
        vendor: "Lavf58.29.100",
        user_comments: {
            "album": "alb",
            "encoder": "Lavc58.54.100 libopus",
            "TRACKNUMBER": "num",
            "DESCRIPTION": "co",
            "artist": "a",
            "title": "t",
            "date": "ye",
            "genre": "ge",
        },
    },
}
```

**Comment by zaethan** [comment]
So it seems like reading metadata actually is the only thing missing for opus support in polaris.
I uploaded my parser [here](https://github.com/zaethan/opus_headers).
I hope I didn't mess it up. It is the first time I created a repository on github.

**Comment by lnicola** [comment]
You didn't mess up but if you don't mind, I'd have a couple of nits about the implementation:

 - `read_bytes` allocates a `Vec` on every call, but it could take a buffer as an argument
 - partial reads are possible in some cases (e.g. network streams or if the process got a signal), you should use `read_exact` if you want a full buffer
 - an `enum Error` would probably be more idiomatic
 - the `to_u32` functions are a bit redundant, and they also incur a lot of bounds checks
   - a trick here is to read the values in the reverse order: `(buf[1], buf[0])`; the difference is that a single bounds check is needed -- note how the index shows up in the panic message, so `(buf[0], buf[1])` throws a different panic message
   - a second one is to do a `let buf = &buf[0..2]` before accessing it
 - but I'd still get rid of them

**Comment by zaethan** [comment]
Thank you for that feedback :D All of that is correct. I will look into it.

- Yes, that vector in `read_bytes` is not great. Initially I wanted to use const generics, but it seems like they are still feature gated and thus require nightly rust, which I wanted to avoid. When I tried to use an array, rustc complained that its size is not known at compile time, which makes sense. To get around this issue I used a Vec, but that has the downside you mentioned. I could add a second parameter and let the caller pass a `mut buffer` which will be filled. In that case, the caller would have to always create a buffer before calling the `read_bytes` function, which is something I wanted to avoid. I will try to find a different solution.
- `read_exact` sounds like a great idea, since I also throw an error if the amount of bytes read does not equal the amount of expected bytes.
- In that case, I probably have to use `map_err()` to map the potential errors of the reader or string conversion to my own error types. Sounds good and would also get rid of the Box.
- The bounds checks could probably be mitigated by adding something like an `assert!(slice.len() >= 4)` before the conversion call, but I agree that removing those functions would be a good idea. I added them because I return a Vec from the `read_bytes` function and wanted to pass the result directly into the conversion function, but they expect arrays.

It seems like most of these issues are arising from how the `read_bytes` function is implemented.

I just looked at the polaris readme again and noticed that it already requires nightly rust. In that case, I assume I can just do the same and make use of const generics. This allows me to return arrays from the `read_bytes` function, which could be directly passed into the `u16::from_le_bytes(...)` functions. No more vec allocations and no more conversion wrappers.

**Comment by zaethan** [comment]
I removed the `read_bytes` and inlined any call to read_exact, as you suggested.
I also use reusable buffers in each method and call the `from_le_bytes` functions directly.
I use multiple buffers, since this allows to read different amounts of bytes.
Finally, I added an ParseError enum, which encapsulates the `UnexpectedEOF`, the `Utf8Error` and my own `DidNotFindHeaders` error.

> I'm also not sure how const generics help there.

You are right, I was misunderstanding what const generics are.

**Comment by agersant** [comment]
Thank you @zaethan for jumping in and @lnicola for the thoughtful review. Reading this thread warms my heart ❤️.

A couple suggestions:
- When you're satisfied with the code, publish your library on `crates.io` so polaris (or other projects) can use it easily. [How to guide](https://doc.rust-lang.org/cargo/reference/publishing.html)
- Add some unit tests, this will make it easier to maintain the library in the long run. I maintain a similar crate for parsing duration of MP3 files, so you can look at [this](https://github.com/agersant/mp3-duration/blob/master/src/test.rs) for reference.
- Add two more public functions which accepts a `&File` and a `AsRef<Path>` (but keep the reader version too). This would be convenient for the most frequent use cases, and also would help users who might not realize that they should use a `BufferedReader`. You can also find examples of this in the `mp3-duration` library above.

**Comment by zaethan** [comment]
Thank you for your feedback :)

I added some tests to test the basic functionality and the rejection of obviously damaged files.
I also added the two extra parse functions you suggested (based on your mp3 crate).
I went ahead and published the current state of the library on `crates.io`. Once again, this is the first time I'm doing this, so I hope I didn't mess it up ^^ (it [does not look like it](https://crates.io/crates/opus_headers) though)

To add opus support to polaris eventually, it looks like we need to add another entry to the `AudioFormat` enum in `utils.rs`.
After that, a new function in the `index/metadata.rs` would need to be added to actually retrieve the metadata. This would essentially be the same as the existing `read_vorbis` function.

**Comment by agersant** [comment]
Awesome!

You are correct about the changes to make in Polaris. If you want to give it a go but you're not sure how to contribute to someone else's project on Github, you can follow [this guide](https://opensource.com/article/19/7/create-pull-request-github) as a starting point.

Let me know if you need any help!

**Comment by zaethan** [comment]
Hey, I created a Pull Request adding opus support.
I contributed to other projects earlier (never had one of my own before), but that guide was a welcome refresher (I initially messed up the branches though :) )

That said, I tested my changes with a set of opus and mp3 files and it seems to be working just fine. The opus files were generated from other mp3's with ffmpeg.

**Comment by agersant** [comment]
Implemented by https://github.com/agersant/polaris/pull/88
