### ISSUE TITLE
Consider using another web framework

### ISSUE THREAD

**Issue by lnicola** [agersant/polaris#68]
I think you've already implemented `actix-web` backend (then removed it, probably due to the controversy around it).

How would you feel about trying [`warp`](https://github.com/seanmonstar/warp/)? I know that Rocket will likely build on stable in a couple of months, but I'm pretty wary of procedural macros because of the build time cost. `warp` is nice in that it doesn't require any macros, though it does have an unusual API.

I've started a `warp` backend and implemented a couple of routes, but it's okay if you're not interested in trying it.

**Comment by agersant** [comment]
I had only done a little bit of work on the `actix-web` backend when the controversy started, it was fairly promising so it may be worth exploring again now that it has a new maintainer.

I did try using `warp` but I gave up after fighting it for 30 minutes. I was never able to find a way to define the routes and endpoints in a way that could be re-used for both `main()` and the API tests. I'm looking forward to seeing what you can get out of it.

I also tried `thruster` and that didn't go anywhere because the static files serving is missing some important features for Polaris (https://github.com/trezm/Thruster/issues/141).

The next on my list was `tide` but I haven't gotten to it yet.

**Comment by lnicola** [comment]
I can put up a PR, but it will take me a long time to implement the full API, so don't hold your breath.

I haven't looked into `thurster` or `gotham` yet, and I'm probably going to give `tide` a pass because of some misunderstandings that resulted in me getting blocked on that repository :confused:.

**Comment by agersant** [comment]
Oh, that is unfortunate :(

Feel free to open a long-running PR if you want to discuss implementation as you go (although I don't know much about `wrap`).

Some things to be mindful of:
- The API tests do not cover enforcement of the Admin API guards, or most error cases. Extra tests would be nice though.
- While compile times are important, I value code clarity in API endpoints more. It's fine if there's a big unwieldy setup somewhere but the individual routes should be as concise as possible. 
- I have no interest in pursuing `async` anything at the moment. (ecosystem feels immature, and Polaris servers are unlikely to serve more concurrent requests than a thread-pool can handle).

**Comment by lnicola** [comment]
Sorry for dropping the ball on this :-(. I guess we can close it, since Rocket will work on stable soon.

**Comment by agersant** [comment]
No worries, I also got very sidetracked from this investigation.
