### ISSUE TITLE
cli doesn't work on Windows

### ISSUE THREAD

**Issue by linsui** [agersant/polaris#81]
I tested `.\polaris.exe -h` but nothing was printed.

**Comment by agersant** [comment]
Uh oh, that's a good find.

I just tested this and I can reproduce the issue, but only with the executable that comes out of the installer (not `cargo run -- -h`).

This executable is linked with `/SUBSYSTEM:WINDOWS` to avoid spawning a console window upon start. Unfortunately, it turns out this also means the executable doesn't get to write to TTY when it's executed within a terminal.

There are tidbits of information hiding in the comments [here](https://stackoverflow.com/questions/7316433/difference-between-console-subsystemconsole-and-windows-subsystemwindows) hinting that this may be fixable.

Note that the arguments you pass in to the program are still working, despite the lack of output. If you want a CLI version of Polaris, you can build one by:

1. Installing the Rust nightly compiler
2. Cloning this repository
3. Executing `cargo build --release`

This will created an executable that is more terminal friendly under `target/release/polaris.exe`.

**Comment by lnicola** [comment]
Wouldn't it be better to set the console subsystem? You could still run it as a service using a helper like https://github.com/rozanski/srvstart.

**Comment by agersant** [comment]
I think I would prefer a solution shipping two executables (`polaris.exe` and `polaris_cli.exe`). This is a pattern I've seen a few times for other popular Windows software (`7-zip` is the first on that comes to mind) and it keeps the learning curve lower.

**Comment by agersant** [comment]
Fixed in release `0.12.4`, there is now a `polaris-cli.exe` in addition to the regular `polaris.exe`.

**Comment by linsui** [comment]
Thanks!
